# [theme]
# primaryColor="#F63366"
# backgroundColor="#FFFFFF"
# secondaryBackgroundColor="#F0F2F6"
# textColor="#262730"
# font="sans serif"

[theme]
primaryColor="#871c1c"              # #871c1c
backgroundColor="#ffffed"           # #ffffed
secondaryBackgroundColor="#e3969c"  # #e3969c
textColor="#000000"                 # #000000
codeBackgroundColor = "#f0d8d8"     # #f0d8d8
font="sans serif"
baseFontSize = 18  

[logger]
level = "info"


